### ISSUE TITLE
TemplateSyntaxError: Encountered unknown tag 'trans'.

### ISSUE THREAD

**Issue by brunic** [farseerfc/pelican-bootstrap3#2]
CRITICAL: TemplateSyntaxError: Encountered unknown tag 'trans'. Jinja was looking for the following tags: 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.

**Comment by brunic** [comment]
I run command "pelican" and show the error above

**Comment by farseerfc** [comment]
You will need to enable `i18n` extension of jinja to run this, try add this line in your pelicanconf.py:

``` python
JINJA_EXTENSIONS = ['jinja2.ext.i18n']
```

BTW this theme depends heavily on my pelican settings here: https://github.com/farseerfc/farseerfc/blob/master/pelicanconf.py
And it also depends on the OS settings. To setup the environment on Ubuntu 12.04 you will need to do these:
https://github.com/farseerfc/farseerfc/blob/master/.travis.yml

If you can read Chinese, there is a description here: http://farseerfc.me/redesign-pelican-theme.html

**Comment by brunic** [comment]
Thanks. 点赞
